#!/bin/bash
# {{PROJECT_NAME}} 실시간 상태 대시보드 생성.
#
# 매 세션 시작·턴 끝·수동 실행 시 호출되어 docs/STATUS.md 갱신.
# 사용자가 새 작업 요청 전 이 파일을 읽으면 전체 팀워크 현황을 한눈에 파악.

set -u

ROOT="/{{project-slug}}"
OUT="$ROOT/docs/STATUS.md"
TMP="$(mktemp)"

cd "$ROOT" 2>/dev/null || exit 0

{
    echo "# {{PROJECT_NAME}} 실시간 상태 대시보드"
    echo
    echo "> 자동 생성 — 매번 덮어씀. 수동 편집 금지."
    echo "> 갱신: \`./docs/scripts/update-status.sh\` 또는 SessionStart/Stop 훅으로 자동."
    echo
    echo "**마지막 갱신**: $(date '+%Y-%m-%d %H:%M:%S %Z')"
    echo
    echo "---"
    echo
    echo "## 워크트리 요약"
    echo
    echo "| 워크트리 | 브랜치 | HEAD | main 대비 | uncommit | 최근 커밋 | 트랙 문서 |"
    echo "|---|---|---|---:|---:|---|---|"

    main_head=$(git -C "$ROOT" rev-parse main 2>/dev/null | cut -c1-7)
    while read -r line; do
        [ -z "$line" ] && continue
        path=$(echo "$line" | awk '{print $1}')
        head=$(echo "$line" | awk '{print $2}')
        branch=$(echo "$line" | sed 's/.*\[\(.*\)\].*/\1/')

        # {{project-slug}} root 는 main 자체이므로 아래 표에선 워크트리들만
        if [ "$path" = "$ROOT" ]; then
            continue
        fi

        name=$(basename "$path")
        ahead_behind=$(git -C "$path" rev-list --left-right --count main...HEAD 2>/dev/null)
        ahead=$(echo "$ahead_behind" | awk '{print $2}')
        behind=$(echo "$ahead_behind" | awk '{print $1}')
        [ -z "$ahead" ] && ahead=0
        [ -z "$behind" ] && behind=0
        diff="+$ahead / -$behind"

        uncommit=$(git -C "$path" status --porcelain 2>/dev/null | wc -l | tr -d ' ')
        last=$(git -C "$path" log -1 --format='%ar: %s' 2>/dev/null | head -c 55)

        track_doc=""
        for cand in "docs/phase1/${name}.md" "docs/phase0/${name}.md"; do
            if [ -f "$ROOT/$cand" ]; then
                track_doc="\`$cand\`"
                break
            fi
        done

        echo "| $name | $branch | $head | $diff | $uncommit | $last | $track_doc |"
    done < <(git -C "$ROOT" worktree list 2>/dev/null)

    echo
    echo "## tmux pane 현황 ({{project-slug}} 세션)"
    echo

    if ! tmux has-session -t {{project-slug}} 2>/dev/null; then
        echo "_세션 없음 (tmux-session.sh 로 기동)_"
    else
        echo "| window | pane | 경로 | 프로세스 | 감지 |"
        echo "|---|---|---|---|---|"
        while read -r line; do
            win=$(echo "$line" | cut -d'|' -f1)
            pane=$(echo "$line" | cut -d'|' -f2)
            path=$(echo "$line" | cut -d'|' -f3)
            cmd=$(echo "$line" | cut -d'|' -f4)
            base=$(basename "$path")

            # Claude 실행 여부 힌트
            tail_content=$(tmux capture-pane -t "{{project-slug}}:${win}.${pane}" -p 2>/dev/null | tail -3 | tr '\n' ' ' | head -c 80)
            if echo "$tail_content" | grep -q "auto mode on\|esc to interrupt\|Claude Code"; then
                hint="🟢 Claude 활성"
            elif echo "$tail_content" | grep -qE "(\$|%|#) *$"; then
                hint="⚪ shell idle"
            else
                hint="…"
            fi

            echo "| $win | $pane | $base | $cmd | $hint |"
        done < <(tmux list-panes -t {{project-slug}} -a -F '#{window_name}|#{pane_index}|#{pane_current_path}|#{pane_current_command}' 2>/dev/null)
    fi

    echo
    echo "## main 최근 커밋 (10개)"
    echo
    echo '```'
    git -C "$ROOT" log main --oneline -10 2>/dev/null
    echo '```'
    echo

    echo "## 원격 동기화"
    echo
    echo '```'
    git -C "$ROOT" status -sb 2>/dev/null | head -1
    origin_main=$(git -C "$ROOT" rev-parse origin/main 2>/dev/null | cut -c1-7)
    echo "origin/main: $origin_main"
    echo "local main:  $main_head"
    echo '```'
    echo

    echo "## 최근 TIMELINE 엔트리 (세션 제목 5개)"
    echo
    if [ -f "$ROOT/docs/TIMELINE.md" ]; then
        grep -m5 '^#### ' "$ROOT/docs/TIMELINE.md" | sed 's/^/- /'
    else
        echo "_TIMELINE 없음_"
    fi
    echo

    echo "## 진행 중 트랙 INIT 문서"
    echo
    for f in $(ls "$ROOT/docs/phase1/"*.md 2>/dev/null) $(ls "$ROOT/docs/phase0/"*.md 2>/dev/null); do
        rel=${f#$ROOT/}
        first_heading=$(grep -m1 '^# ' "$f" | head -c 70)
        echo "- \`$rel\` — $first_heading"
    done
    echo

    echo "## 사용자 다음 요청 배정 힌트"
    echo
    echo "새 요청 들어오면 오케스트레이터는 다음 순서로 판단:"
    echo "1. 요청 내용 → 어느 트랙 INIT 문서와 매칭?"
    echo "2. 해당 워크트리 tmux pane 이 Claude 활성? → 그 pane 에 지시 송신"
    echo "3. 관련 트랙 없으면 → 새 워크트리/pane 신설 제안"
    echo "4. 큰 결정(main push·외부 repo·데이터 삭제) → 사용자에게 직접 확인"
    echo

    echo "---"
    echo
    echo "_Generated by \`docs/scripts/update-status.sh\`_"
} > "$TMP"

mv "$TMP" "$OUT"
echo "✅ docs/STATUS.md 갱신 완료 ($(wc -l < "$OUT" | tr -d ' ')줄)"
